### PR TITLE
Removed 4K sector size limit. V2

### PR DESCRIPTION
**Pull request by PoeticDeath**
Removed 4K sector size limit. Without increasing sector byte size by using 2 << value, instead of just value. Because the sector size is required to be a power of two anyway this works with no negative effects.

----

Before submitting this PR please review this checklist. Ideally all checkmarks should be checked upon submitting. (Use an x inside square brackets like so: [x])

- [x] **Contributing**: You MUST read and be willing to accept the [CONTRIBUTOR AGREEMENT](https://github.com/winfsp/winfsp/blob/master/Contributors.asciidoc). The agreement gives joint copyright interests in your contributions to you and the original WinFsp author. If you have already accepted the [CONTRIBUTOR AGREEMENT](https://github.com/winfsp/winfsp/blob/master/Contributors.asciidoc) you do not need to do so again.
- [ ] **Topic branch**: Avoid creating the PR off the master branch of your fork. Consider creating a topic branch and request a pull from that. This allows you to add commits to the master branch of your fork without affecting this PR.
- [x] **No tabs**: Consistently use SPACES everywhere. NO TABS, unless the file format requires it (e.g. Makefile).
- [x] **Style**: Follow the same code style as the rest of the project.
- [ ] **Tests**: Include tests to the extent that it is possible, especially if you add a new feature.
- [x] **Quality**: Your design and code should be of high quality and something that you are proud of.

### CODE REVIEW

**Comment by billziss-gh** [comment]
@PoeticDeath 

I appreciate your hacking happily away at this problem, but would you mind setting up an AppVeyor account for yourself to try your experiments? Your PR updates constantly spin WinFsp builds on AppVeyor that take long time to complete. As a result I cannot use AppVeyor for my own purposes.

Also you should know that I have some doubts regarding your effort to increase the sector size:

- I doubt that it is possible to go past the 4096 page size on Windows. For example, when using buffered I/O or memory mapped files, the memory manager has to fetch pages and it likely assumes that the page size (4096) is always greater or equal to the sector size. Thus it may send requests aligned at 4096 bytes to the file system even if you specify your sector size as higher.

- Unbuffered I/O on Windows has special alignment requirements that can be easily met by using the page size for alignment and that is what many applications use. This is also official advice from Microsoft: https://learn.microsoft.com/en-us/windows/win32/fileio/file-buffering#alignment-and-file-access-requirements

    > Because buffer addresses for read and write operations must be sector-aligned, the application must have direct control of how these buffers are allocated. One way to sector-align buffers is to use the [VirtualAlloc](https://learn.microsoft.com/en-us/windows/desktop/api/memoryapi/nf-memoryapi-virtualalloc) function to allocate the buffers.

- Even if you did succeed in raising the sector size, I am uncertain what you would gain. If it is speed you are after, simply turn on the cache manager by specifying `FileInfoTimeout = -1` and then the OS will perform I/O at sizes much higher than 4096 bytes.

**Comment by PoeticDeath** [comment]
I didn't realize there was a free tier... or that concurrent jobs are restricted. I was looking for the ifstest executable but couldn't find it anywhere for local testing. I'll setup my own account. I'll reopen when I get something that tests checkout on.

**Comment by billziss-gh** [comment]
Just reuse the `appveyor.yml` file included with WinFsp and it will get all necessary dependencies for you.

**Comment by PoeticDeath** [comment]
The tests pass now, I guess code review is needed. Assuming there are no complaints... we can merge. I could not find where the page size was specified, but you could get a speed boost from switching from small to large pages. Perhaps with an optional parameter.

**Comment by PoeticDeath** [comment]
Use SectorsPerAllocationUnit and save yourself some time...

**Pull request closed without merging**
